### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by ytaylordev** [Adalab/modulo-1-evaluacion-final-Lourdesjupo#1]
Muy buen trabajo @Lourdesjupo  !!!

Aquí tienes unos consejos para mejorar tu ejercicio:

- [ ] HTML > ATRIBUTOS: Todos los `a` o `img` que tengan interactividad deben tener el atributo `title`.
- [x] HTML > HAMBURGUESA: El menú de la hamburguesa debe tener un `nav`.
- [x] CSS > INTERACCIÓN: Intenta usar alguna animación CSS para llamar la atención de la usuaria.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits también tienen que ser en inglés, empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Con cada mejora que hagas, marcarla como completada en este issue y su súbela a este repo.

> Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by Lourdesjupo** [comment]
Hola @ytaylordev !
He completado el segundo punto (pusheado) : HTML > HAMBURGUESA: El menú de la hamburguesa debe tener un nav. 

He completado el tercer punto (pusheado): INTERACCIÓN: Intenta usar alguna animación CSS para llamar la atención de la usuaria. Incluí una animación con keyframes en el titulo y subtitulo del hero. 

(No incluí ninguna animación antes, porque no quise recargar mucho la página, pensé que con la animación de los botones up/down cuando los pulsas, el cambio de color de los btn cuando los pulsas y el smoth para el scroll sería suficiente.)

Respecto a incluir el atributo title, no entendí muy bien que debo hacer. No incluí ningún tag de img en mi código y en el caso de los anchor apliqué el title en los botones para desplazarse por la página ( flechas up/down) y el anchor del menú hamburguesa,.

Mi duda es, si debo incluir title en el resto de los anchor, a pesar que estos tienen texto (botones/ menu footer),  ya que asumo que en todos ellos el usuario puede interactuar con ellos (clickar). Para que sirve este tag en los anchor que no son imágenes, ¿no sería dar información redundante y podría confundir al usuario?

Muchas gracias por todos los consejos !!

**Comment by ytaylordev** [comment]
Hola Lourdes, 

- Con respecto a al animación el objetivo es que practiques con ellas y sepas que existen por i las necesitas en algún momento. Si no te gusta incluirlas en este caso puedes luego con vista a tu portafolio eliminarlas. 
- Sobre el primer punto incluir el atributo `title` en las imágenes o enlaces, en este caso se refiere a los enlaces: El title es un atributo de los links que nos permite indicar el un texto descriptivo del enlace y sólo podemos verlo en la web dejando el puntero del ratón quieto sobre el enlace en cuestión.  Este atributo ayuda a completar el significado del link y se usa para temas de SEO: https://github.com/Adalab/modulo-1-evaluacion-final-Lourdesjupo/blob/1ec205c1094282b2e48bd0df8e5235035244b2d6/src/html/partials/link.html#LL1C1-L1C47

Espero que te haya quedado más claro a que me refería :)

**Comment by Lourdesjupo** [comment]
Hola Yanelis, 

Gracias por la explicación! ya he modificado los links de la página para que aparezca title. 

Gracias!
